import io
from typing import Dict, Any
from xml.sax.saxutils import escape
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from backend.verification.result import VerificationResult
from backend.models.document import display_document_type


def safe_text(value: Any) -> str:
    return escape(str(value))


class NumberedCanvas(canvas.Canvas):
    """
    Canvas subclass to dynamically calculate page numbers and render professional headers/footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Footer divider line
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 612 - 54, 45)

        # Footer Content
        self.drawString(54, 32, "Generated by PropVerify")
        self.drawRightString(612 - 54, 32, f"Page {self._pageNumber} of {page_count}")
        disclaimer = "This report is an automated document verification summary and should be reviewed by an appropriate professional before making legal or financial decisions."
        self.drawString(54, 20, disclaimer)

        self.restoreState()


def generate_pdf_report(result: VerificationResult) -> bytes:
    """
    Generates a PDF verification report bytes from VerificationResult JSON data.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=60
    )

    styles = getSampleStyleSheet()

    primary_color = colors.HexColor("#0284c7")
    dark_color = colors.HexColor("#0f172a")

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=dark_color,
        spaceAfter=2
    )

    subtitle_style = ParagraphStyle(
        "ReportSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=primary_color,
        spaceAfter=10
    )

    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=dark_color,
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12.5,
        textColor=colors.HexColor("#334155")
    )

    table_header_style = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1e293b")
    )

    story = []

    # Title Banner
    story.append(Paragraph("PropVerify", title_style))
    story.append(Paragraph("PROPERTY DOCUMENT VERIFICATION REPORT", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=primary_color, spaceAfter=12))

    # 1. VERIFICATION SUMMARY
    story.append(Paragraph("1. VERIFICATION SUMMARY", heading_style))

    is_clean = result.overall_status == "VERIFIED"
    status_hex = "#16a34a" if is_clean else "#d97706"
    if is_clean:
        status_label = "✓ VERIFIED / CLEAN"
    else:
        status_label = f"⚠ {result.overall_status.replace('_', ' ')}"

    summary_data = [
        [
            Paragraph("<b>Overall Status</b>", body_style),
            Paragraph(f"<font color='{status_hex}'><b>{safe_text(status_label)}</b></font>", body_style)
        ],
        [Paragraph("<b>Documents Processed</b>", body_style), Paragraph(str(result.documents_processed), body_style)],
        [Paragraph("<b>Fields Evaluated</b>", body_style), Paragraph(str(len(result.matches) + len(result.mismatches) + len(result.missing_fields)), body_style)],
        [Paragraph("<b>Matched Fields</b>", body_style), Paragraph(str(len(result.matches)), body_style)],
        [Paragraph("<b>Mismatched Fields</b>", body_style), Paragraph(str(len(result.mismatches)), body_style)],
        [Paragraph("<b>Missing Fields</b>", body_style), Paragraph(str(len(result.missing_fields)), body_style)],
        [Paragraph("<b>Missing Documents</b>", body_style), Paragraph(str(len(result.missing_documents)), body_style)],
    ]

    summary_table = Table(summary_data, colWidths=[160, 344])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 8))

    # 2. REQUIRED DOCUMENTS
    story.append(Paragraph("2. REQUIRED DOCUMENTS", heading_style))
    req_docs = result.required_documents or []
    missing_doc_types = [m.expected_document_type for m in result.missing_documents]

    req_rows = []
    for doc_type in req_docs:
        doc_type_label = display_document_type(doc_type)
        if doc_type in missing_doc_types:
            req_rows.append([
                Paragraph(f"<font color='#b45309'>⚠ <b>{safe_text(doc_type_label)}</b></font>", body_style),
                Paragraph("<font color='#b45309'><b>MISSING — Not Provided</b></font>", body_style)
            ])
        else:
            req_rows.append([
                Paragraph(f"<font color='#16a34a'>✓ <b>{safe_text(doc_type_label)}</b></font>", body_style),
                Paragraph("<font color='#15803d'>Provided</font>", body_style)
            ])

    if req_rows:
        req_table = Table(req_rows, colWidths=[180, 324])
        req_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('PADDING', (0, 0), (-1, -1), 4.5),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(req_table)
    story.append(Spacer(1, 8))

    # 3. VERIFICATION RESULTS TABLE
    story.append(Paragraph("3. VERIFICATION RESULTS", heading_style))

    results_data = [[
        Paragraph("<b>Field</b>", table_header_style),
        Paragraph("<b>Status</b>", table_header_style),
        Paragraph("<b>Details</b>", table_header_style)
    ]]

    for m in result.mismatches:
        field_name = m.field.replace("_", " ").title()
        results_data.append([
            Paragraph(f"<b>{safe_text(field_name)}</b>", body_style),
            Paragraph("<font color='#dc2626'><b>⚠ MISMATCH</b></font>", body_style),
            Paragraph(safe_text(m.message), body_style)
        ])

    for m in result.matches:
        field_name = m.field.replace("_", " ").title()
        results_data.append([
            Paragraph(safe_text(field_name), body_style),
            Paragraph("<font color='#16a34a'><b>✓ MATCH</b></font>", body_style),
            Paragraph(safe_text(m.matched_value), body_style)
        ])

    for missing in result.missing_fields:
        field_name = missing.field.replace("_", " ").title()
        results_data.append([
            Paragraph(safe_text(field_name), body_style),
            Paragraph("<font color='#b45309'><b>MISSING</b></font>", body_style),
            Paragraph(safe_text(missing.message), body_style)
        ])

    res_table = Table(results_data, colWidths=[130, 90, 284])
    res_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('PADDING', (0, 0), (-1, -1), 4.5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(res_table)
    story.append(Spacer(1, 10))

    # 4. ISSUES DETECTED
    if result.mismatches:
        story.append(Paragraph("4. ISSUES DETECTED (FIELD MISMATCHES)", heading_style))
        for m in result.mismatches:
            field_title = m.field.replace("_", " ").title()
            issue_story = []
            issue_story.append(Paragraph(f"<b>{safe_text(field_title)}</b> — <font color='#dc2626'><b>Severity: {safe_text(m.severity)}</b></font>", body_style))
            issue_story.append(Spacer(1, 3))
            issue_story.append(Paragraph(f"<i>Explanation:</i> {safe_text(m.message)}", body_style))
            issue_story.append(Spacer(1, 3))

            val_rows = [[Paragraph("<b>Document File</b>", table_header_style), Paragraph("<b>Extracted Value</b>", table_header_style)]]
            conflicting_documents = set(m.conflicting_documents)
            for fname, val in m.values.items():
                is_diff = fname in conflicting_documents
                val_text = f"<font color='#dc2626'><b>{safe_text(val)} ⚠</b></font>" if is_diff else safe_text(val)
                val_rows.append([Paragraph(safe_text(fname), body_style), Paragraph(val_text, body_style)])

            val_table = Table(val_rows, colWidths=[180, 324])
            val_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#fee2e2")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#fca5a5")),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            issue_story.append(val_table)
            issue_story.append(Spacer(1, 8))
            story.append(KeepTogether(issue_story))

    # 5. MISSING DOCUMENTS
    story.append(Paragraph("5. MISSING DOCUMENTS", heading_style))
    if not result.missing_documents:
        story.append(Paragraph("<font color='#16a34a'>✓ All required documents were provided in the uploaded set.</font>", body_style))
    else:
        for md in result.missing_documents:
            story.append(Paragraph(
                f"<font color='#b45309'>⚠ <b>{safe_text(display_document_type(md.expected_document_type))}</b> (Severity: {safe_text(md.severity)}) — {safe_text(md.message)}</font>",
                body_style
            ))
            story.append(Spacer(1, 3))

    # 6. EXTRACTED DOCUMENT INFORMATION
    if result.processed_documents:
        story.append(Paragraph("6. EXTRACTED DOCUMENT INFORMATION", heading_style))
        for processed in result.processed_documents:
            title = f"{display_document_type(processed.document_type_detected)} — {processed.file_name}"
            story.append(Paragraph(f"<b>{safe_text(title)}</b>", body_style))
            if processed.ai_used:
                method = "Structured extraction: AI"
            else:
                method = "Structured extraction: deterministic"
            if processed.ocr_used:
                method += " · OCR used"
            story.append(Paragraph(safe_text(method), body_style))
            extracted_rows = [[Paragraph("<b>Field</b>", table_header_style), Paragraph("<b>Extracted value</b>", table_header_style)]]
            for field_name, field_value in processed.extracted_data.model_dump(exclude_none=True).items():
                if field_name != "document_type" and str(field_value).strip():
                    extracted_rows.append([Paragraph(safe_text(field_name.replace("_", " ").title()), body_style), Paragraph(safe_text(field_value), body_style)])
            if len(extracted_rows) > 1:
                extracted_table = Table(extracted_rows, colWidths=[160, 344], repeatRows=1)
                extracted_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ('PADDING', (0, 0), (-1, -1), 4),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ]))
                story.append(extracted_table)
            else:
                story.append(Paragraph("No structured fields were extracted.", body_style))
            story.append(Spacer(1, 8))

    if result.warnings:
        story.append(Paragraph("7. PROCESSING WARNINGS", heading_style))
        for warning in result.warnings:
            story.append(Paragraph(f"• {safe_text(warning)}", body_style))
            story.append(Spacer(1, 3))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
